name: Build Godot w/ optimization (32-bit)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable multilib and refresh mirrors
        run: |
          set -euxo pipefail
          if ! grep -q '^\[multilib\]' /etc/pacman.conf; then
            cat >> /etc/pacman.conf <<'EOF'

          [core]
          Include = /etc/pacman.d/mirrorlist
          
          [multilib]
          Include = /etc/pacman.d/mirrorlist
          EOF
          fi
          pacman-key --init || true
          pacman-key --populate archlinux || true
          pacman -Syu --noconfirm

      - name: Install build & runtime dependencies (best effort)
        run: |
          set -euxo pipefail
          # core build deps (ensure these are present)
          pacman -S --noconfirm --needed base-devel git scons yasm setconf mold || true

          # install a broad set of lib32 runtime deps (pacman will skip ones not found)
          PKG32=(
            lib32-brotli
            lib32-freetype2
            lib32-libglvnd
            lib32-libtheora
            lib32-libvorbis
            lib32-libwebp
            lib32-libxcursor
            lib32-libxi
            lib32-libxinerama
            lib32-libxrandr
            lib32-pcre2
            lib32-alsa-lib
            lib32-pulseaudio
            lib32-glib2
            lib32-graphite
            lib32-libsquish
            lib32-libwslay
            lib32-miniupnpc
            lib32-openxr
            pulse-native-provider
          )

          for p in "${PKG32[@]}"; do
            echo "attempting install: $p"
            pacman -S --noconfirm --needed "$p" || echo "package $p not found/available, skipping"
          done

      - name: Create build user and set permissions
        run: |
          set -euxo pipefail
          useradd -m builder || true
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build package as builder (no -s)
        run: |
          set -euxo pipefail
          su - builder -c "cd $GITHUB_WORKSPACE && makepkg -p PKGBUILD-perf --noconfirm"

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: "*.pkg.tar.zst"
